name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CC: gcc-11
      CXX: g++-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Print compiler version
      run: ${{ env.CC }} --version

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Version range or exact version of a Python version to use, using SemVer's version range syntax

    - name: Install meson
      run: |
        python -m pip install --upgrade pip
        pip install meson

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3
      with:
        version: 1.10.2

    - name: Install zimg
      run: |
        git clone https://github.com/sekrit-twc/zimg --branch v3.0 --depth 1
        pushd zimg
        ./autogen.sh
        ./configure --disable-static --disable-simd
        make -j2
        sudo make install -j2
        popd

    - name: Install VapourSynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --depth 1
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-static --disable-x86-asm --disable-vsscript --disable-vspipe --disable-python-module --disable-plugins
        make -j2
        sudo make install -j2
        popd

    - name: Install Vulkan loader library
      run: |
        sudo apt-get update
        sudo apt-get install libvulkan-dev

    - name: Build
      run: |
        meson build
        ninja -C build
